language: python

python:
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0

env:
  matrix:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Precise 12.04
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.4"
      COVERAGE=true
    # This environment tests the oldest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MKL="false"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0" CYTHON_VERSION="0.23"
      COVERAGE=true
    # This environment tests the more recent anaconda env.
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MKL="true"
      NUMPY_VERSION="1.11.2" SCIPY_VERSION="0.18.1" CYTHON_VERSION="0.25.2" 
      COVERAGE=true

# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script: pytest inverse_covariance