language: python
python: 2.7

sudo: false

# Pre-install packages for the ubuntu distribution
cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt: true
    packages:
        - libatlas3gf-base
        - libatlas-dev
        - python-scipy

# command to install dependencies
install:
    - pip install -U pip wheel    
    - pip install --install-option="--no-cython-compile" cython
    - pip install -r requirements.txt
    - python setup.py develop

# command to run tests
script: python -m pytest --showlocals --pyargs
